// ===========================================
// Premium Animated Background
// ===========================================

document.addEventListener("DOMContentLoaded", () => {

    const bg = document.querySelector(".background");

    if (!bg) return;

    // =====================================
    // Floating Bubbles
    // =====================================

    const bubbleCount = 35;

    for (let i = 0; i < bubbleCount; i++) {

        const bubble = document.createElement("div");

        bubble.className = "bubble";

        const size = Math.random() * 60 + 15;

        bubble.style.width = size + "px";
        bubble.style.height = size + "px";

        bubble.style.left = Math.random() * 100 + "%";

        bubble.style.animationDuration =
            (15 + Math.random() * 20) + "s";

        bubble.style.animationDelay =
            Math.random() * 20 + "s";

        bubble.style.opacity =
            (Math.random() * 0.25 + 0.05);

        bg.appendChild(bubble);

    }

    // =====================================
    // Particles
    // =====================================

    const particleCount = 120;

    for (let i = 0; i < particleCount; i++) {

        const particle = document.createElement("div");

        particle.className = "particle";

        const size = Math.random() * 3 + 1;

        particle.style.width = size + "px";
        particle.style.height = size + "px";

        particle.style.left = Math.random() * 100 + "%";
        particle.style.top = Math.random() * 100 + "%";

        particle.style.animationDuration =
            (20 + Math.random() * 20) + "s";

        particle.style.animationDelay =
            Math.random() * 20 + "s";

        bg.appendChild(particle);

    }

    // =====================================
    // Glow Orbs
    // =====================================

    const orbCount = 5;

    for (let i = 0; i < orbCount; i++) {

        const orb = document.createElement("div");

        orb.className = "glow-orb";

        const size = Math.random() * 250 + 180;

        orb.style.width = size + "px";
        orb.style.height = size + "px";

        orb.style.left = Math.random() * 100 + "%";
        orb.style.top = Math.random() * 100 + "%";

        orb.style.animationDuration =
            (25 + Math.random() * 15) + "s";

        bg.appendChild(orb);

    }

    // =====================================
    // Cursor Spotlight
    // =====================================

    const light = document.createElement("div");

    light.className = "cursor-light";

    document.body.appendChild(light);

    document.addEventListener("mousemove", e => {

        light.style.left = e.clientX + "px";
        light.style.top = e.clientY + "px";

    });

// =====================================
// Continuous Shooting Stars
// =====================================

// function createStar() {

//     const star = document.createElement("div");
//     star.className = "shooting-star";

//     // Start somewhere in the upper 60% of the screen
//     star.style.left = (Math.random() * window.innerWidth) + "px";
//     star.style.top = (Math.random() * window.innerHeight * 0.6) + "px";

//     // Random tail length
//     star.style.width = (120 + Math.random() * 180) + "px";

//     // Random speed
//     star.style.animationDuration = (1.2 + Math.random() * 1.3) + "s";

//     // Random brightness
//     star.style.opacity = (0.6 + Math.random() * 0.4);

//     // Slightly different angles
//     const angle = -25 + Math.random() * 20;
//     star.style.setProperty("--angle", angle + "deg");

//     bg.appendChild(star);

//     star.addEventListener("animationend", () => {
//         star.remove();
//     });

// }

// Create a new star every 700ms
setInterval(createStar, 700);

// Create 2–3 stars together
function starShower() {

    const total = Math.floor(Math.random() * 2) + 2; // 2 or 3

    for (let i = 0; i < total; i++) {

        setTimeout(() => {

            createStar();

        }, i * 250);

    }

}

// Start immediately
starShower();

// Repeat every 4–7 seconds
setInterval(() => {

    starShower();

}, 4000 + Math.random() * 3000);

    setInterval(createStar, 5000);

});


// ===========================================
// CSS Generated by JS
// ===========================================

const style = document.createElement("style");

style.innerHTML = `

.bubble{

position:absolute;
bottom:-120px;

border-radius:50%;

background:
radial-gradient(circle at 30% 30%,
rgba(255,255,255,.45),
rgba(59,130,246,.20),
rgba(59,130,246,.03));

backdrop-filter:blur(2px);

animation:bubbleFloat linear infinite;

}

@keyframes bubbleFloat{

0%{
transform:translateY(0) translateX(0);
}

50%{
transform:translateY(-55vh)
translateX(30px);
}

100%{
transform:translateY(-130vh)
translateX(-30px);
}

}

.particle{

position:absolute;

border-radius:50%;

background:white;

opacity:.35;

animation:particleMove linear infinite alternate;

}

@keyframes particleMove{

from{

transform:translate(0,0);

}

to{

transform:translate(45px,-70px);

}

}

.glow-orb{

position:absolute;

border-radius:50%;

filter:blur(80px);

background:

radial-gradient(circle,

rgba(59,130,246,.18),

transparent 70%);

animation:orbMove ease-in-out infinite alternate;

}

@keyframes orbMove{

from{

transform:translate(0,0);

}

to{

transform:translate(150px,-120px);

}

}

.cursor-light{

position:fixed;

width:350px;
height:350px;

pointer-events:none;

transform:translate(-50%,-50%);

border-radius:50%;

filter:blur(80px);

background:

radial-gradient(circle,

rgba(59,130,246,.22),

transparent 70%);

z-index:-1;

transition:left .08s linear,
top .08s linear;

}

.shooting-star{

position:absolute;

width:180px;
height:2px;

background:

linear-gradient(to right,
white,
rgba(255,255,255,0));

transform:rotate(-35deg);

animation:shoot 2s linear forwards;

}

@keyframes shoot{

from{

transform:
translate(0,0)
rotate(-35deg);

opacity:1;

}

to{

transform:
translate(-500px,500px)
rotate(-35deg);

opacity:0;

}

}
`;

document.head.appendChild(style);

